# 影响的世界
worlds:
  - world_the_end
# 龙最大血量
dragon-max-health: 2048.0
# 随机刻发生速度 tick speed
random-tick-period: 700
# 技能结束后选择延迟
skill-pick-latency: 400
# 技能列表
skills:
  dragon-effect-cloud: # 龙息云
    # 技能持续时间（结束后会消除影响）
    duration: 400
    # 药水云持续时间
    cloud-duration: 60
    # 药水云展开距离
    radius: 10
    # 药水云生成间隔
    check-interval: 25
    # 技能即将开始提示信息
    broadcast:
      - "<random_other_player_name>：这条龙比以前的都要强，那它的口水……"
      - "<random_other_player_name>：我去，真带劲的臭口水，我可不想在里面洗澡！"
      - "<player_name>：找掩体躲一下！"
      - "<random_other_player_name>：话说这能拿来炼药吗……"
  throws: # 地球上投
    duration: 200
    # 上抛玩家时刻
    time: 100
    # 上抛叠加向量
    velocity-x: 0.0
    velocity-y: 100.0
    velocity-z: 0.0
    broadcast:
      - "<dragon_name>：地上的生灵，如果失去坚实的土地，就无能为力了吧！"
      - "<dragon_name>：「立足之处」被剥夺的感受，也体验一下吧！"
  # 苦力怕乘TNT - 摧毁末地大陆！
  rocket-rain: # 龙炎火雨
    duration: 250
    check-interval: 10
    creeper-explode-radius: 10
    creeper-powered: true
    creeper-fuse-ticks: 100
    creeper-health: 40.0
    creeper-auto-ignite: true
    creeper-speed-duration: 250
    creeper-speed-level: 2
    broadcast:
      - "<dragon_name>：艺术就是爆炸，而你……将在爆炸中消失！"
      - "<dragon_name>：够了，该结束这场闹剧了！给我灰飞烟灭吧！"
      - "<dragon_name>：我们一概追求核平，见识下核平的力量吧！"
  trident: # 天降三叉戟
    duration: 250
    check-interval: 10
    height: 80
    broadcast:
      - "<random_other_player_name>：检测到大量下落的不明物体！"
      - "<random_other_player_name>：检测到强烈的电离磁场云，注意防范雷电！"
      - "<player_name>：我看到了什么？雷神天闪？"
  nuke: # 核爆
    duration: 220
    # 激活核弹爆炸的时刻
    explode-time: 200
    # 参考：普通苦力怕为 3，TNT是 4，闪电苦力怕是 6
    power: 25.0
    broadcast:
      - "<dragon_name>：末日的钟声响起了，人类，一切都将在爆炸的火焰中陨灭！"
      - |
        <player_name>：这条龙它疯了，它想和我们同归于尽！
        <random_other_player_name>：远离中心祭坛！
        <player_name>：远离中心祭坛还不够！远离主岛范围！
  ravage: # 末影复仇
    duration: 600
    check-interval: 10
    range: 100
    broadcast:
      - "<dragon_name>：我的子民们，团结起来，将这些无知人类从我们的故乡驱逐出去！"
      - "<dragon_name>：蝼蚁们，是时候也让你们尝尝人海战术的滋味了！"
  warden: # 监守者之力
    warden-health: 80.0
    broadcast:
      - "&5末影龙：&r我以末地之主的名义召唤，漆黑之梦魇，出现吧！"
  shulker-on-phantom: # 潜影浮现
    amount: 10
    broadcast:
      - "<dragon_name>：让愚蠢的人类离开他们引以为傲的陆地吧！"
      - "<dragon_name>：潜影一族，听我号令，进攻！"
      - |
        RCF：检测到幻翼一族活动的声呐信号。
        <random_other_player_name>：（当场拿出收割黑夜）
  grouped-wolfs: #狼群出动
    amount: 3
    broadcast:
      - "<dragon_name>：我的随从啊！让这些人类尝尝利齿撕咬的滋味吧！"
      - |
        <random_other_player_name>：笑死，它召唤的好像是狗哎！等下，草这不是一般的狗，这是疯狗！
        <player_name>：兄弟，这是狼！你们有带骨头吗？
  loud-roar: # 大声咆哮
    potion-duration: 600
    potion-level: 1
    broadcast:
      - |
        <dragon_name>：可恶的人类！（大声咆哮）
        <player_name>：让我想起了我家的姜黄猫，猛虎咆哮.jpg
  flame-boom: # 烈焰眩晕
    max-amount: 7
    fire-ticks: 600
    darkness-ticks: 200
    damage: 5
    broadcast:
      - <dragon_name>：感受一下龙炎的炙热吧！
  breath-lock-link: # 龙息束链
    duration: 200
    broadcast:
      - <player_name>：卧槽好粘稠的口水！
        <random_other_player_name>：回到总部我一定要狠狠地洗澡！
    link-hit:
      - 被粘住了，可恶
  wind: # 邪风
    duration: 100
    # 受影响范围
    range: 150
    broadcast:
      - |
        <random_other_player_name>：<dragon_name>停下来了，这条该死的龙在做什么？
        <random_other_player_name>：不对劲，这附近的气流也停滞下来了！
      - |
        <player_name>：大家快落地！飞行装置失灵了，<dragon_name>正利用这点想要击飞所有在场的东西！
        <random_other_player_name>：我去外面是虚空，小心别掉进去！
      - <dragon_name>：不懂得生命的可贵，自然也不理解狂风的凛冽！
      - 'RCF: 小队注意，你们所在附近的风场变的十分不稳定，大的要来了，抓好附近的东西，别被吹飞了！'
  wither-shield: # 凋零护盾
    wither-max-amounts: 6
    wither-max-health: 100
    end-broadcast: "凋零护盾已被击破，干得漂亮！"
    broadcast:
      - "<random_other_player_name>：各小队注意，末影龙召唤了凋零护盾，干掉这些凋零才能突破末影龙的防线，位置已经标出在你们的显示屏上，我们上吧。"
  skeleton-shooter: # 飞天狙
    skeleton-shooter-spawn-height: 10.0
    skeleton-shooter-max-health: 50
    bow-damage-enchantment-level: 5
    broadcast: "<dragon_name>：队友呢？队友救一下啊队友!"
  # 【被动】 末影龙 HP 低于该值时禁用爆炸伤害
  explosion-protect:
    below: 150.0
  # 【被动】 末影龙 HP 低于该值时禁用远程伤害
  projectile-protect:
    below: 80.0
team-skills:
  get-ready:
    broadcast: "&aRCF 终结技 &b[%s&b]&a 准备就绪，&b点击此处施放终结技！"
  active:
    broadcast: "&c<player_name>: &f现在施放终结技 &b[%s&b]&a！"
  purge:
    name: "&6肃静"
    broadcast:
      - "<player_name>: 是时候让世界安静一些了！让嘈杂的声音就此消失吧！末影超声炮！（战场的所有末影人已全部击杀）"
    need-charge: 3600
# 召唤物名字
summon-entity-name: "Codusk"
# Ding~ 随 机 选 人
dragon-name:
  - "鳕龙"
  - "艾 尔 登 之 龙"
  - "癫火之龙"
  - "旺财"
  - "红暴大轮胎"
  - "莉亚电钻杀人魔"
  - "极地邪魅地头蛇"
  - "莉亚菇菇"
  - "河豚气鼓鼓"
  - "香烤鳕鱼"
  - "狗"
  - "RIAZth | 候车厅"
# 开战标题
fight-start:
  title: "&a┗|｀O′|┛ 嗷~~"
  subtitle: "&6末地之王正在虚无中翱翔！"
fight-end:
  egg-placed: "&7曾经的末地之主已倒在你的面前，只剩一颗龙蛋孤独的落在传送门之上...\n不过你知道，它终有一天还会归来。休息一下，做好下次讨伐的准备吧"
attributes:
  GENERIC_MAX_HEALTH:
    ADD_NUMBER_DEMO:
      amount: 5.0
      operation: "ADD_NUMBER"
    MULTIPLY_SCALAR_1_DEMO:
      amount: 0.5
      operation: "MULTIPLY_SCALAR_1"
    ADD_SCALAR:
      amount: 1.5
      operation: "ADD_SCALAR"
stay-together:
  group-says:
    - "快过来，人多力量大"
    - "终于来了，RCF 小队绝不丢下任何队员"
    - "别放弃，我们都在！"
    - "下次别跑的太远了，欢迎回来"
  alone-says:
    - "我来了，搭把手！"
    - "帮我一下，一起对付它！"
    - "搭把手！"
    - "我来了"